kind: pipeline
type: docker
name: frontend-pr

trigger:
  event:
    - pull_request

steps:
  - name: test
    image: node:24.11.1-bookworm
    environment:
      CI: "true"
      # Drone runners are often memory-constrained; TS typecheck/build can OOM without a larger heap.
      NODE_OPTIONS: "--max-old-space-size=2048"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    commands:
      - corepack enable
      - node --version
      - yarn --version
      - yarn install --immutable
      # Run unit tests on PRs; full suite (typecheck/lint/build) can be run on push/release pipelines.
      - yarn vitest
