kind: pipeline
type: docker
name: frontend-pr

trigger:
  event:
    - pull_request

steps:
  - name: test
    image: node:24.11.1-bookworm
    environment:
      CI: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    commands:
      - corepack enable
      - node --version
      - yarn --version
      - yarn install --immutable
      - yarn test

