import type { Meta, StoryObj } from '@storybook/react';
import { createStoryDecorator } from '@/stories/storyUtils';
import { PeriodCard } from './PeriodCard';

const meta: Meta<typeof PeriodCard> = {
  title: 'Components/Periods/PeriodCard',
  component: PeriodCard,
  tags: ['autodocs'],
  decorators: [createStoryDecorator()],
};

export default meta;
type Story = StoryObj<typeof PeriodCard>;

const basePeriod = {
  id: 'per-1',
  name: 'February 2026',
  startDate: '2026-02-01',
  endDate: '2026-02-28',
  isAutoGenerated: false,
};

export const Current: Story = {
  args: {
    period: basePeriod,
    status: 'current',
    onEdit: () => {},
    onDelete: () => {},
  },
};

export const Upcoming: Story = {
  args: {
    period: {
      ...basePeriod,
      id: 'per-2',
      name: 'March 2026',
      startDate: '2026-03-01',
      endDate: '2026-03-31',
    },
    status: 'upcoming',
    onEdit: () => {},
    onDelete: () => {},
  },
};

export const Past: Story = {
  args: {
    period: {
      ...basePeriod,
      id: 'per-0',
      name: 'January 2026',
      startDate: '2026-01-01',
      endDate: '2026-01-31',
    },
    status: 'past',
    onEdit: () => {},
    onDelete: () => {},
  },
};

export const AutoGenerated: Story = {
  args: {
    period: { ...basePeriod, isAutoGenerated: true },
    status: 'current',
    onEdit: () => {},
    onDelete: () => {},
  },
};
