import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import * as useBudget from '@/hooks/useBudget';
import { fireEvent, render, screen } from '@/test-utils';
import { PeriodsPage } from './PeriodsPage';

const TODAY = new Date();
const formatDate = (date: Date) => date.toISOString().slice(0, 10);
const addDays = (days: number) => {
  const next = new Date(TODAY);
  next.setDate(next.getDate() + days);
  return next;
};

const mockPeriods = [
  {
    id: 'current-1',
    name: 'Current Window',
    startDate: formatDate(addDays(-3)),
    endDate: formatDate(addDays(3)),
    isAutoGenerated: false,
    transactionCount: 4,
  },
  {
    id: 'upcoming-1',
    name: 'Upcoming Window',
    startDate: formatDate(addDays(8)),
    endDate: formatDate(addDays(15)),
    isAutoGenerated: true,
    transactionCount: 0,
  },
  {
    id: 'past-1',
    name: 'Past Window',
    startDate: formatDate(addDays(-20)),
    endDate: formatDate(addDays(-10)),
    isAutoGenerated: false,
    transactionCount: 12,
  },
];

const renderPeriodsPage = () =>
  render(
    <MemoryRouter>
      <PeriodsPage />
    </MemoryRouter>
  );

vi.mock('@/hooks/useBudget', async () => {
  const actual = await vi.importActual('@/hooks/useBudget');
  return {
    ...actual,
    useBudgetPeriods: vi.fn(),
    useBudgetPeriodSchedule: vi.fn(),
    useBudgetPeriodGaps: vi.fn(),
    useDeleteBudgetPeriod: vi.fn(() => ({ mutateAsync: vi.fn() })),
    useDeleteBudgetPeriodSchedule: vi.fn(() => ({ mutateAsync: vi.fn(), isPending: false })),
    useUpdateBudgetPeriod: vi.fn(() => ({ mutateAsync: vi.fn() })),
  };
});

vi.mock('@/hooks/useDisplayCurrency', () => ({
  useDisplayCurrency: () => ({
    id: 'cur-jpy',
    name: 'Japanese Yen',
    symbol: '¥',
    currency: 'JPY',
    decimalPlaces: 0,
  }),
}));

describe('PeriodsPage', () => {
  beforeEach(() => {
    vi.mocked(useBudget.useBudgetPeriods).mockReturnValue({
      data: mockPeriods,
      isLoading: false,
    } as any);
    vi.mocked(useBudget.useBudgetPeriodGaps).mockReturnValue({
      data: { unassignedCount: 0, transactions: [] },
      isLoading: false,
    } as any);
    vi.mocked(useBudget.useBudgetPeriodSchedule).mockReturnValue({
      data: {
        id: 'schedule-1',
        startDay: 1,
        durationValue: 1,
        durationUnit: 'months',
        generateAhead: 6,
      },
      isLoading: false,
    } as any);
  });

  it('renders redesigned sections with current schedule upcoming and past structure', () => {
    renderPeriodsPage();

    expect(screen.getByRole('heading', { name: /Budget Periods/i })).toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /Create Period/i })).not.toBeInTheDocument();
    expect(screen.getByRole('button', { name: /Edit Schedule/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /Current Period/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /^Schedule$/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /Upcoming Periods/i })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: /Past Periods/i })).toBeInTheDocument();
  });

  it('shows create period button when schedule is absent', () => {
    vi.mocked(useBudget.useBudgetPeriodSchedule).mockReturnValue({
      data: null,
      isLoading: false,
    } as any);

    renderPeriodsPage();

    expect(screen.getByRole('button', { name: /Create Period/i })).toBeInTheDocument();
  });

  it('renders compact card affordances with view action and auto-generated marker', async () => {
    renderPeriodsPage();

    fireEvent.click(screen.getByRole('button', { name: /Toggle past periods/i }));

    expect(screen.getAllByRole('link', { name: /^View budget period$/i }).length).toBeGreaterThan(
      0
    );
    expect(screen.getByText(/^Auto$/i)).toBeInTheDocument();
    expect(screen.queryByText(/Auto-generated/i)).not.toBeInTheDocument();
  });

  it('shows detailed warnings when disabling schedule', async () => {
    renderPeriodsPage();

    // Click Disable Schedule button
    const disableBtn = screen.getByRole('button', { name: /Disable Schedule/i });
    fireEvent.click(disableBtn);

    // Check for detailed warnings in the modal
    expect(await screen.findByText(/Disable Auto-Creation\?/i)).toBeInTheDocument();
    expect(await screen.findByText(/Stop automatic period creation/i)).toBeInTheDocument();
    expect(await screen.findByText(/Delete unused future periods/i)).toBeInTheDocument();
    expect(
      await screen.findByText(/Convert periods with transactions to manual periods/i)
    ).toBeInTheDocument();
  });

  it('formats gap transaction amounts using display currency settings', () => {
    vi.mocked(useBudget.useBudgetPeriodGaps).mockReturnValue({
      data: {
        unassignedCount: 1,
        transactions: [
          {
            id: 'gap-tx-1',
            description: 'Coffee',
            occurredAt: new Date().toISOString(),
            amount: 1234,
          },
        ],
      },
      isLoading: false,
    } as any);

    renderPeriodsPage();

    expect(screen.getByText(/(?:¥|￥)\s?1,234/)).toBeInTheDocument();
  });
});
