import dayjs from 'dayjs';
import { useMemo, useState } from 'react';
import {
  IconAlertTriangle,
  IconChevronDown,
  IconChevronUp,
  IconPlayerPause,
  IconRefresh,
  IconSettings,
} from '@tabler/icons-react';
import { useTranslation } from 'react-i18next';
import {
  ActionIcon,
  Alert,
  Badge,
  Button,
  Group,
  Loader,
  Modal,
  Paper,
  Select,
  Stack,
  Text,
  Title,
} from '@mantine/core';
import {
  useBudgetPeriodGaps,
  useBudgetPeriods,
  useBudgetPeriodSchedule,
  useDeleteBudgetPeriod,
  useDeleteBudgetPeriodSchedule,
  useUpdateBudgetPeriod,
} from '@/hooks/useBudget';
import { useDisplayCurrency } from '@/hooks/useDisplayCurrency';
import { toast } from '@/lib/toast';
import { BudgetPeriod, BudgetPeriodGaps } from '@/types/budget';
import { formatCurrency } from '@/utils/currency';
import { PeriodCard } from './PeriodCard';
import { PeriodFormModal } from './PeriodFormModal';
import { ScheduleSettingsModal } from './ScheduleSettingsModal';
import classes from './PeriodsPage.module.css';

const sortByStartDateDesc = (left: BudgetPeriod, right: BudgetPeriod) =>
  dayjs(right.startDate).valueOf() - dayjs(left.startDate).valueOf();

interface GapRange {
  startDate: string;
  endDate: string;
}

const getGapRange = (transactions: BudgetPeriodGaps['transactions']): GapRange | null => {
  if (transactions.length === 0) {
    return null;
  }

  const ordered = [...transactions].sort(
    (left, right) => dayjs(left.occurredAt).valueOf() - dayjs(right.occurredAt).valueOf()
  );

  return {
    startDate: dayjs(ordered[0].occurredAt).format('YYYY-MM-DD'),
    endDate: dayjs(ordered[ordered.length - 1].occurredAt).format('YYYY-MM-DD'),
  };
};

const mergePeriodWithGapRange = (period: BudgetPeriod, gapRange: GapRange): GapRange => {
  const periodStart = dayjs(period.startDate);
  const periodEnd = dayjs(period.endDate);
  const gapStart = dayjs(gapRange.startDate);
  const gapEnd = dayjs(gapRange.endDate);

  return {
    startDate: (periodStart.isBefore(gapStart) ? periodStart : gapStart).format('YYYY-MM-DD'),
    endDate: (periodEnd.isAfter(gapEnd) ? periodEnd : gapEnd).format('YYYY-MM-DD'),
  };
};

const overlapsAnyPeriod = (
  startDate: string,
  endDate: string,
  periods: BudgetPeriod[],
  currentPeriodId?: string
) => {
  const start = dayjs(startDate);
  const end = dayjs(endDate);

  return periods.some((existingPeriod) => {
    if (existingPeriod.id === currentPeriodId) {
      return false;
    }

    const existingStart = dayjs(existingPeriod.startDate);
    const existingEnd = dayjs(existingPeriod.endDate);

    return (
      start.isBefore(existingEnd.add(1, 'day')) && end.isAfter(existingStart.subtract(1, 'day'))
    );
  });
};

export function PeriodsPage() {
  const { t, i18n } = useTranslation();
  const globalCurrency = useDisplayCurrency();
  const { data: periods = [], isLoading: isLoadingPeriods } = useBudgetPeriods();
  const { data: schedule, isLoading: isLoadingSchedule } = useBudgetPeriodSchedule();
  const { data: gaps, isLoading: isLoadingGaps } = useBudgetPeriodGaps();
  const deletePeriodMutation = useDeleteBudgetPeriod();
  const disableScheduleMutation = useDeleteBudgetPeriodSchedule();
  const updatePeriodMutation = useUpdateBudgetPeriod();

  const [isPastOpen, setIsPastOpen] = useState(false);
  const [isPeriodModalOpen, setPeriodModalOpen] = useState(false);
  const [isGapResolutionModalOpen, setGapResolutionModalOpen] = useState(false);
  const [isScheduleModalOpen, setScheduleModalOpen] = useState(false);
  const [editingPeriod, setEditingPeriod] = useState<BudgetPeriod | null>(null);
  const [selectedGapPeriodId, setSelectedGapPeriodId] = useState<string | null>(null);
  const [periodPendingDelete, setPeriodPendingDelete] = useState<BudgetPeriod | null>(null);
  const [isDisableScheduleConfirmOpen, setDisableScheduleConfirmOpen] = useState(false);
  const [suggestedRange, setSuggestedRange] = useState<{
    startDate: string;
    endDate?: string;
  } | null>(null);

  const now = dayjs().startOf('day');

  const groupedPeriods = useMemo(() => {
    const current = periods.filter(
      (period) =>
        dayjs(period.startDate).startOf('day').isBefore(now.add(1, 'day')) &&
        dayjs(period.endDate).startOf('day').isAfter(now.subtract(1, 'day'))
    );

    const upcoming = periods
      .filter((period) => dayjs(period.startDate).startOf('day').isAfter(now))
      .sort(sortByStartDateDesc);

    const past = periods
      .filter((period) => dayjs(period.endDate).startOf('day').isBefore(now))
      .sort(sortByStartDateDesc);

    return {
      current: current.sort(sortByStartDateDesc),
      upcoming,
      past,
    };
  }, [now, periods]);

  const gapRange = useMemo(() => getGapRange(gaps?.transactions ?? []), [gaps?.transactions]);

  const editablePeriods = useMemo(
    () => periods.filter((period) => !period.isAutoGenerated).sort(sortByStartDateDesc),
    [periods]
  );

  const selectedGapPeriod = useMemo(
    () => editablePeriods.find((period) => period.id === selectedGapPeriodId) ?? null,
    [editablePeriods, selectedGapPeriodId]
  );

  const mergedGapRange = useMemo(() => {
    if (!selectedGapPeriod || !gapRange) {
      return null;
    }

    return mergePeriodWithGapRange(selectedGapPeriod, gapRange);
  }, [gapRange, selectedGapPeriod]);

  const hasGapCoverageChanges =
    Boolean(selectedGapPeriod && mergedGapRange) &&
    (selectedGapPeriod?.startDate !== mergedGapRange?.startDate ||
      selectedGapPeriod?.endDate !== mergedGapRange?.endDate);

  const hasOverlapConflict =
    Boolean(mergedGapRange && selectedGapPeriod) &&
    overlapsAnyPeriod(
      mergedGapRange!.startDate,
      mergedGapRange!.endDate,
      periods,
      selectedGapPeriod!.id
    );

  const openCreateModal = () => {
    setEditingPeriod(null);
    setSuggestedRange(null);
    setPeriodModalOpen(true);
  };

  const openEditModal = (period: BudgetPeriod) => {
    setEditingPeriod(period);
    setSuggestedRange(null);
    setPeriodModalOpen(true);
  };

  const handleDelete = (period: BudgetPeriod) => {
    setPeriodPendingDelete(period);
  };

  const confirmDelete = async () => {
    if (!periodPendingDelete) {
      return;
    }

    try {
      await deletePeriodMutation.mutateAsync(periodPendingDelete.id);
      toast.success({
        title: t('common.success'),
        message: t('periods.deletedSuccess'),
      });
      setPeriodPendingDelete(null);
    } catch (error) {
      toast.error({
        title: t('common.error'),
        message: error instanceof Error ? error.message : t('periods.deleteFailed'),
        nonCritical: true,
        action: {
          label: t('common.retry'),
          onClick: () => {
            void confirmDelete();
          },
        },
      });
    }
  };

  const confirmDisableSchedule = async () => {
    try {
      await disableScheduleMutation.mutateAsync();
      toast.success({
        title: t('common.success'),
        message: t('periods.schedule.disabledSuccess'),
      });
      setDisableScheduleConfirmOpen(false);
    } catch (error) {
      toast.error({
        title: t('common.error'),
        message: error instanceof Error ? error.message : t('periods.schedule.failedToSave'),
        nonCritical: true,
      });
    }
  };

  const handleFixGap = () => {
    if (gapRange) {
      setSuggestedRange(gapRange);
    }

    setGapResolutionModalOpen(false);
    setEditingPeriod(null);
    setPeriodModalOpen(true);
  };

  const openGapResolutionModal = () => {
    setSelectedGapPeriodId((current) => {
      if (current && editablePeriods.some((period) => period.id === current)) {
        return current;
      }

      return editablePeriods[0]?.id ?? null;
    });
    setGapResolutionModalOpen(true);
  };

  const handleExtendPeriodToCoverGap = async () => {
    if (!selectedGapPeriod || !mergedGapRange) {
      return;
    }

    if (hasOverlapConflict) {
      toast.error({
        title: t('common.error'),
        message: t('periods.gaps.overlapConflict'),
        nonCritical: true,
      });
      return;
    }

    if (!hasGapCoverageChanges) {
      toast.info({
        title: t('common.info'),
        message: t('periods.gaps.noCoverageChange'),
      });
      return;
    }

    try {
      await updatePeriodMutation.mutateAsync({
        id: selectedGapPeriod.id,
        payload: {
          name: selectedGapPeriod.name,
          startDate: mergedGapRange.startDate,
          endDate: mergedGapRange.endDate,
        },
      });

      toast.success({
        title: t('common.success'),
        message: t('periods.gaps.extendSuccess'),
      });
      setGapResolutionModalOpen(false);
    } catch (error) {
      toast.error({
        title: t('common.error'),
        message: error instanceof Error ? error.message : t('periods.gaps.extendFailed'),
        nonCritical: true,
      });
    }
  };

  if (isLoadingPeriods || isLoadingSchedule || isLoadingGaps) {
    return (
      <div className={classes.loadingState}>
        <Loader size="sm" />
      </div>
    );
  }

  return (
    <Stack gap="xl" className={classes.pageRoot}>
      <Group justify="space-between" align="flex-start" className={classes.headerRow}>
        <Stack gap={4}>
          <Title order={1}>{t('periods.page.title')}</Title>
          <Text c="dimmed">{t('periods.page.description')}</Text>
        </Stack>

        {!schedule && <Button onClick={openCreateModal}>{t('periods.createPeriod')}</Button>}
      </Group>

      {schedule ? (
        <section className={classes.scheduleSection}>
          <Group justify="space-between" align="center" mb="md">
            <Title order={3}>{t('periods.schedule.sectionTitle')}</Title>
          </Group>
          <Paper withBorder radius="lg" p="lg" className={classes.scheduleCard}>
            <Group justify="space-between" align="flex-start" gap="md">
              <Stack gap={4}>
                <Group gap="xs">
                  <Text fw={700}>{t('periods.schedule.activeTitle')}</Text>
                  <Badge color="violet" variant="light">
                    {t('periods.schedule.activeBadge')}
                  </Badge>
                </Group>
                <Text size="sm" c="dimmed">
                  {t('periods.schedule.summary', {
                    startDay: schedule.startDay,
                    durationValue: schedule.durationValue,
                    durationUnit: t(`periods.modal.durationUnits.${schedule.durationUnit}`),
                    generateAhead: schedule.generateAhead,
                  })}
                </Text>
              </Stack>

              <Group gap="xs">
                <Button
                  variant="light"
                  leftSection={<IconSettings size={14} />}
                  onClick={() => setScheduleModalOpen(true)}
                >
                  {t('periods.schedule.edit')}
                </Button>
                <Button
                  color="red"
                  variant="light"
                  leftSection={<IconPlayerPause size={14} />}
                  onClick={() => setDisableScheduleConfirmOpen(true)}
                  loading={disableScheduleMutation.isPending}
                >
                  {t('periods.schedule.disable')}
                </Button>
              </Group>
            </Group>
          </Paper>
        </section>
      ) : (
        <section className={classes.scheduleSection}>
          <Group justify="space-between" align="center" mb="md">
            <Title order={3}>{t('periods.schedule.sectionTitle')}</Title>
          </Group>
          <Paper withBorder radius="lg" p="lg" className={classes.setupCard}>
            <Stack gap={4}>
              <Text fw={700}>{t('periods.schedule.notConfiguredTitle')}</Text>
              <Text size="sm" c="dimmed">
                {t('periods.schedule.notConfiguredDescription')}
              </Text>
            </Stack>

            <Button
              leftSection={<IconRefresh size={14} />}
              onClick={() => setScheduleModalOpen(true)}
            >
              {t('periods.schedule.configure')}
            </Button>
          </Paper>
        </section>
      )}

      {(gaps?.unassignedCount ?? 0) > 0 && (
        <Alert
          color="orange"
          variant="light"
          icon={<IconAlertTriangle size={18} />}
          title={t('periods.gaps.title', { count: gaps?.unassignedCount ?? 0 })}
        >
          <Stack gap="sm" mt="xs">
            <Text size="sm">{t('periods.gaps.subtitle')}</Text>
            {(gaps?.transactions ?? []).slice(0, 3).map((transaction) => (
              <Group
                key={transaction.id}
                justify="space-between"
                className={classes.gapTransaction}
              >
                <Text size="sm">
                  {dayjs(transaction.occurredAt).format('MMM D')} - {transaction.description}
                </Text>
                <Text size="sm" fw={700}>
                  {formatCurrency(transaction.amount, globalCurrency, i18n.language)}
                </Text>
              </Group>
            ))}
            <Button size="xs" color="orange" variant="filled" onClick={openGapResolutionModal}>
              {t('periods.gaps.resolveAction')}
            </Button>
          </Stack>
        </Alert>
      )}

      <section className={`${classes.section} ${classes.currentSection}`}>
        <Group justify="space-between">
          <Title order={3} className={classes.sectionLabel}>
            {t('periods.sections.current')}
          </Title>
        </Group>

        <Stack gap="md" mt="md">
          {groupedPeriods.current.length > 0 ? (
            groupedPeriods.current.map((period) => (
              <PeriodCard
                key={period.id}
                period={period}
                status="current"
                onEdit={openEditModal}
                onDelete={handleDelete}
              />
            ))
          ) : (
            <Text c="dimmed">{t('periods.empty.current')}</Text>
          )}
        </Stack>
      </section>

      <section className={`${classes.section} ${classes.upcomingSection}`}>
        <Group justify="space-between">
          <Title order={3} className={classes.sectionLabel}>
            {t('periods.sections.upcoming')}
          </Title>
          <Badge variant="light" color="gray">
            {groupedPeriods.upcoming.length}
          </Badge>
        </Group>

        <Stack gap="md" mt="md">
          {groupedPeriods.upcoming.length > 0 ? (
            groupedPeriods.upcoming.map((period) => (
              <PeriodCard
                key={period.id}
                period={period}
                status="upcoming"
                onEdit={openEditModal}
                onDelete={handleDelete}
              />
            ))
          ) : (
            <Text c="dimmed">{t('periods.empty.upcoming')}</Text>
          )}
        </Stack>

        <Text size="xs" c="dimmed" mt="sm" className={classes.upcomingDisclaimer}>
          {t('periods.upcomingDisclaimer')}
        </Text>
      </section>

      <section className={`${classes.section} ${classes.pastSection}`}>
        <Group justify="space-between" align="center">
          <Title order={3} className={classes.sectionLabel}>
            {t('periods.sections.past')}
          </Title>
          <Group gap="xs">
            <Badge variant="light" color="gray">
              {groupedPeriods.past.length}
            </Badge>
            <ActionIcon
              variant="subtle"
              color="gray"
              onClick={() => setIsPastOpen((current) => !current)}
              aria-label="Toggle past periods"
            >
              {isPastOpen ? <IconChevronUp size={16} /> : <IconChevronDown size={16} />}
            </ActionIcon>
          </Group>
        </Group>

        {isPastOpen && (
          <Stack gap="md" mt="md">
            {groupedPeriods.past.length > 0 ? (
              groupedPeriods.past.map((period) => (
                <PeriodCard
                  key={period.id}
                  period={period}
                  status="past"
                  onEdit={openEditModal}
                  onDelete={handleDelete}
                />
              ))
            ) : (
              <Text c="dimmed">{t('periods.empty.past')}</Text>
            )}
          </Stack>
        )}
      </section>

      <PeriodFormModal
        opened={isPeriodModalOpen}
        onClose={() => {
          setPeriodModalOpen(false);
          setEditingPeriod(null);
          setSuggestedRange(null);
        }}
        periods={periods}
        period={editingPeriod}
        suggestedRange={suggestedRange}
      />

      <ScheduleSettingsModal
        opened={isScheduleModalOpen}
        onClose={() => setScheduleModalOpen(false)}
        schedule={schedule ?? null}
      />

      <Modal
        opened={isGapResolutionModalOpen}
        onClose={() => setGapResolutionModalOpen(false)}
        title={t('periods.gaps.resolveTitle')}
        centered
      >
        <Stack gap="md">
          <Text size="sm">{t('periods.gaps.subtitle')}</Text>

          {gapRange && (
            <Text size="sm" c="dimmed">
              {t('periods.gaps.rangeSummary', {
                start: dayjs(gapRange.startDate).format('MMM D, YYYY'),
                end: dayjs(gapRange.endDate).format('MMM D, YYYY'),
              })}
            </Text>
          )}

          <Button size="sm" color="orange" variant="light" onClick={handleFixGap}>
            {t('periods.gaps.fixAction')}
          </Button>

          <Select
            label={t('periods.gaps.extendPeriodLabel')}
            placeholder={t('periods.gaps.extendPeriodPlaceholder')}
            data={editablePeriods.map((period) => ({
              label: `${period.name} (${dayjs(period.startDate).format('MMM D')} - ${dayjs(period.endDate).format('MMM D')})`,
              value: period.id,
            }))}
            value={selectedGapPeriodId}
            onChange={(value) => setSelectedGapPeriodId(value)}
            disabled={editablePeriods.length === 0}
            clearable={false}
          />

          {editablePeriods.length === 0 ? (
            <Text size="sm" c="dimmed">
              {t('periods.gaps.noEditablePeriods')}
            </Text>
          ) : (
            selectedGapPeriod &&
            mergedGapRange && (
              <div className={classes.gapPreviewCard}>
                <Text size="xs" c="dimmed">
                  {t('periods.gaps.previewTitle')}
                </Text>
                <Text size="sm">
                  {t('periods.gaps.currentRange', {
                    start: dayjs(selectedGapPeriod.startDate).format('MMM D, YYYY'),
                    end: dayjs(selectedGapPeriod.endDate).format('MMM D, YYYY'),
                  })}
                </Text>
                <Text size="sm" fw={700}>
                  {t('periods.gaps.updatedRange', {
                    start: dayjs(mergedGapRange.startDate).format('MMM D, YYYY'),
                    end: dayjs(mergedGapRange.endDate).format('MMM D, YYYY'),
                  })}
                </Text>
              </div>
            )
          )}

          {hasOverlapConflict && (
            <Alert color="red" variant="light" icon={<IconAlertTriangle size={16} />}>
              {t('periods.gaps.overlapConflict')}
            </Alert>
          )}

          <Group justify="flex-end">
            <Button variant="subtle" onClick={() => setGapResolutionModalOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button
              onClick={handleExtendPeriodToCoverGap}
              loading={updatePeriodMutation.isPending}
              disabled={!selectedGapPeriod || !mergedGapRange || hasOverlapConflict}
            >
              {t('periods.gaps.extendAction')}
            </Button>
          </Group>
        </Stack>
      </Modal>

      <Modal
        opened={Boolean(periodPendingDelete)}
        onClose={() => setPeriodPendingDelete(null)}
        title={t('budget.budgetedCategories.delete')}
        centered
      >
        <Stack gap="md">
          <Text>
            {t('periods.confirmDelete', {
              name: periodPendingDelete?.name ?? '',
            })}
          </Text>
          <Group justify="flex-end">
            <Button variant="subtle" onClick={() => setPeriodPendingDelete(null)}>
              {t('common.cancel')}
            </Button>
            <Button color="red" onClick={confirmDelete} loading={deletePeriodMutation.isPending}>
              {t('budget.budgetedCategories.delete')}
            </Button>
          </Group>
        </Stack>
      </Modal>

      <Modal
        opened={isDisableScheduleConfirmOpen}
        onClose={() => setDisableScheduleConfirmOpen(false)}
        title={t('periods.schedule.disableWarningTitle')}
        centered
      >
        <Stack gap="md">
          <Alert icon={<IconAlertTriangle size={16} />} variant="light" color="orange">
            <Text fw={700} mb="xs">
              {t('periods.schedule.disableWarningIntro')}
            </Text>
            <Stack gap={4}>
              <Text size="sm">• {t('periods.schedule.disableWarningStop')}</Text>
              <Text size="sm">• {t('periods.schedule.disableWarningDelete')}</Text>
              <Text size="sm">• {t('periods.schedule.disableWarningConvert')}</Text>
              <Text size="sm">• {t('periods.schedule.disableWarningManual')}</Text>
            </Stack>
          </Alert>
          <Text size="sm">{t('periods.schedule.disableWarningOutro')}</Text>
          <Group justify="flex-end">
            <Button variant="subtle" onClick={() => setDisableScheduleConfirmOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button
              color="red"
              onClick={confirmDisableSchedule}
              loading={disableScheduleMutation.isPending}
            >
              {t('periods.schedule.disable')}
            </Button>
          </Group>
        </Stack>
      </Modal>
    </Stack>
  );
}
