import dayjs from 'dayjs';
import { IconChartBar, IconClock, IconEdit, IconLock, IconTrash } from '@tabler/icons-react';
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import { ActionIcon, Badge, Card, Group, Stack, Text } from '@mantine/core';
import { BudgetPeriod } from '@/types/budget';
import classes from './PeriodsPage.module.css';

interface PeriodCardProps {
  period: BudgetPeriod;
  status: 'current' | 'upcoming' | 'past';
  onEdit: (period: BudgetPeriod) => void;
  onDelete: (period: BudgetPeriod) => void;
}

const getMetaValue = (period: BudgetPeriod, status: PeriodCardProps['status']) => {
  if (status === 'current') {
    return dayjs(period.endDate).diff(dayjs().startOf('day'), 'day');
  }

  if (status === 'upcoming') {
    return dayjs(period.startDate).diff(dayjs().startOf('day'), 'day');
  }

  return dayjs().startOf('day').diff(dayjs(period.endDate), 'day');
};

export function PeriodCard({ period, status, onEdit, onDelete }: PeriodCardProps) {
  const { t } = useTranslation();
  const metaValue = getMetaValue(period, status);
  const isLocked = Boolean(period.isAutoGenerated);
  const autoGeneratedLabel = `${t('periods.autoBadge')}-generated`;
  const badgeLabel =
    status === 'current'
      ? t('periods.sections.current')
      : status === 'upcoming'
        ? t('periods.sections.upcoming')
        : t('periods.sections.past');

  return (
    <Card
      withBorder
      radius="lg"
      className={`${status === 'current' ? classes.currentCard : classes.periodCard} ${classes.periodCardCompact}`}
    >
      <Group justify="space-between" align="center" mb="xs">
        <Stack gap={2}>
          <Group gap="xs">
            <Text fw={700}>{period.name}</Text>
            <Badge size="xs" variant="light" color={status === 'current' ? 'cyan' : 'gray'}>
              {badgeLabel}
            </Badge>
            {isLocked && (
              <Badge size="xs" variant="light" color="violet" leftSection={<IconLock size={10} />}>
                {autoGeneratedLabel}
              </Badge>
            )}
            {period.isConverted && (
              <Badge size="xs" variant="light" color="orange" leftSection={<IconEdit size={10} />}>
                {t('periods.convertedBadge')}
              </Badge>
            )}
          </Group>
          <Text size="sm" c="dimmed">
            {dayjs(period.startDate).format('MMM D')} - {dayjs(period.endDate).format('MMM D')} (
            {dayjs(period.endDate).diff(dayjs(period.startDate), 'day')} {t('periods.days')})
          </Text>
        </Stack>

        <Group gap="xs" className={classes.periodActions}>
          <ActionIcon
            variant="subtle"
            color="gray"
            component={Link}
            to="/budget"
            aria-label="View"
          >
            <IconChartBar size={16} />
          </ActionIcon>
          <ActionIcon
            variant="subtle"
            color="blue"
            disabled={isLocked}
            onClick={() => onEdit(period)}
            aria-label="Edit period"
          >
            <IconEdit size={16} />
          </ActionIcon>
          <ActionIcon
            variant="subtle"
            color="red"
            disabled={isLocked}
            onClick={() => onDelete(period)}
            aria-label="Delete period"
          >
            <IconTrash size={16} />
          </ActionIcon>
        </Group>
      </Group>

      <Group className={`${classes.metaRow} ${classes.metaRowCompact}`}>
        <Group gap={6}>
          <IconClock size={14} />
          <Text size="sm" c="dimmed">
            {status === 'current'
              ? t('periods.card.daysRemaining', { count: Math.max(metaValue, 0) })
              : status === 'upcoming'
                ? t('periods.card.startsIn', { count: Math.max(metaValue, 0) })
                : t('periods.card.endedAgo', { count: Math.max(metaValue, 0) })}
          </Text>
        </Group>
        <Text size="sm" fw={600}>
          {t('periods.card.transactionsCount', { count: period.transactionCount ?? 0 })}
        </Text>
      </Group>
    </Card>
  );
}
