import type { Meta, StoryObj } from '@storybook/react';
import { PeriodCard } from './PeriodCard';

const basePeriod = {
  id: 'period-current',
  name: 'February 2026',
  startDate: '2026-02-01',
  endDate: '2026-02-28',
  transactionCount: 27,
};

const meta: Meta<typeof PeriodCard> = {
  title: 'Components/Periods/PeriodCard',
  component: PeriodCard,
  args: {
    onEdit: () => {},
    onDelete: () => {},
  },
};

export default meta;
type Story = StoryObj<typeof PeriodCard>;

export const Current: Story = {
  args: {
    period: basePeriod,
    status: 'current',
  },
};

export const UpcomingAuto: Story = {
  args: {
    period: {
      ...basePeriod,
      id: 'period-upcoming',
      name: 'March 2026',
      startDate: '2026-03-01',
      endDate: '2026-03-31',
      isAutoGenerated: true,
      transactionCount: 0,
    },
    status: 'upcoming',
  },
};

export const Past: Story = {
  args: {
    period: {
      ...basePeriod,
      id: 'period-past',
      name: 'January 2026',
      startDate: '2026-01-01',
      endDate: '2026-01-31',
      transactionCount: 43,
    },
    status: 'past',
  },
};
