import { CategoryResponse } from '@/types/category';

export interface BudgetResponse {
  id: string;
  name: string;
  startDay: number;
}

export interface BudgetRequest {
  name: string;
  startDay: number;
}

export interface BudgetCategoryResponse {
  id: string;
  categoryId: string;
  budgetedValue: number;
  category: CategoryResponse;
}

export interface BudgetCategoryRequest {
  categoryId: string;
  budgetedValue: number;
}

export interface BudgetPeriod {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  isAutoGenerated?: boolean;
  transactionCount?: number;
  budgetUsedPercentage?: number;
}

export interface BudgetPeriodRequest {
  name: string;
  startDate: string;
  endDate: string;
  copyBudgetsFromPrevious?: boolean;
}

export type PeriodDurationUnit = 'days' | 'weeks' | 'months';

export type WeekendAdjustment = 'keep' | 'friday' | 'monday';

export interface BudgetPeriodSchedule {
  id: string;
  startDay: number;
  durationValue: number;
  durationUnit: PeriodDurationUnit;
  saturdayAdjustment: WeekendAdjustment;
  sundayAdjustment: WeekendAdjustment;
  namePattern: string;
  generateAhead: number;
}

export interface BudgetPeriodScheduleRequest {
  startDay: number;
  durationValue: number;
  durationUnit: PeriodDurationUnit;
  saturdayAdjustment: WeekendAdjustment;
  sundayAdjustment: WeekendAdjustment;
  namePattern: string;
  generateAhead: number;
}

export interface PeriodGapTransaction {
  id: string;
  occurredAt: string;
  description: string;
  amount: number;
}

export interface BudgetPeriodGaps {
  unassignedCount: number;
  transactions: PeriodGapTransaction[];
}
